### ISSUE TITLE
Poison.encode raises FunctionClauseError on invalid utf-8 binaries

### ISSUE THREAD

**Issue by manukall** [devinus/poison#128]
```elixir
iex(1)> Poison.encode(%{test: <<253, 99>>})
** (FunctionClauseError) no function clause matching in Poison.Encoder.BitString.chunk_size/3
    (poison) lib/poison/encoder.ex:139: Poison.Encoder.BitString.chunk_size(<<253, 99>>, nil, 0)
    (poison) lib/poison/encoder.ex:134: Poison.Encoder.BitString.escape/2
    (poison) lib/poison/encoder.ex:88: Poison.Encoder.BitString.encode/2
    (poison) lib/poison/encoder.ex:227: anonymous fn/4 in Poison.Encoder.Map.encode/3
    (poison) lib/poison/encoder.ex:228: Poison.Encoder.Map."-encode/3-lists^foldl/2-0-"/3
    (poison) lib/poison/encoder.ex:228: Poison.Encoder.Map.encode/3
    (poison) lib/poison.ex:41: Poison.encode!/2
    (poison) lib/poison.ex:15: Poison.encode/2
```

I would expect something like `{:error, {:invalid, <<253, 99>>}}` here.

**Comment by lexmag** [comment]
It happens when input contains broken UTF-8 codepoint, only part of it for example:
```elixir
"й"
#=> <<208, 185>>
"йc"
#=> <<208, 185, 99>>
Poison.encode(<<208, 99>>)
** (FunctionClauseError) no function clause matching in Poison.Encoder.BitString.chunk_size/3
```
Note, I dropped `185` byte from `"й"` codepoint.

**Comment by devinus** [comment]
This behaviour has been changed in https://github.com/devinus/poison/commit/62e98f19552289f3f7139aca438ce2b169c54796.
