### ISSUE TITLE
`Poison.decode(nil)` raises `ArgumentError`

### ISSUE THREAD

**Issue by aYukiSekiguchi** [devinus/poison#226]
4.0.1
```
iex(1)> Poison.decode(nil)
{:error, %Poison.ParseError{pos: 0, rest: nil, value: nil}}
```

master and 6.0.0
```
iex(1)> Poison.decode(nil)
** (ArgumentError) errors were found at the given arguments:

  * 1st argument: not an iodata term

    (erts 15.0) :erlang.iolist_to_binary(nil)
    (poison 6.0.0) lib/poison/parser.ex:100: Poison.Parser.parse!/2
    (poison 6.0.0) lib/poison.ex:104: Poison.decode/2
    iex:1: (file)
```

I understand `nil` is an invalid value, so this may be not a bug.

**Comment by aYukiSekiguchi** [comment]
Sorry. It looks like this is same as https://github.com/devinus/poison/issues/203 and this is intentional.

I'll wait for feedback for few days, but I'll close if there is no feedback.
