### ISSUE TITLE
Trouble encoding nil

### ISSUE THREAD

**Issue by tpitale** [devinus/poison#43]
Using `"poison": {:hex, :poison, "1.5.0"},`

```
    ** (Poison.EncodeError) unable to encode value: {nil, "shows"}
        (poison) lib/poison/encoder.ex:339: Poison.Encoder.Any.encode/2
        (poison) lib/poison/encoder.ex:213: anonymous fn/4 in Poison.Encoder.Map.encode/3
        (poison) lib/poison/encoder.ex:214: Poison.Encoder.Map."-encode/3-lists^foldl/2-0-"/3
        (poison) lib/poison/encoder.ex:214: Poison.Encoder.Map.encode/3
        (poison) lib/poison/encoder.ex:213: anonymous fn/4 in Poison.Encoder.Map.encode/3
        (poison) lib/poison/encoder.ex:214: Poison.Encoder.Map."-encode/3-lists^foldl/2-0-"/3
        (poison) lib/poison/encoder.ex:214: Poison.Encoder.Map.encode/3
        (poison) lib/poison/encoder.ex:232: anonymous fn/3 in Poison.Encoder.List.encode/3
        (poison) lib/poison/encoder.ex:233: Poison.Encoder.List."-encode/3-lists^foldr/2-1-"/3
        (poison) lib/poison/encoder.ex:233: Poison.Encoder.List.encode/3
        (poison) lib/poison.ex:41: Poison.encode!/2
        (phoenix) lib/phoenix/controller.ex:628: Phoenix.Controller.do_render/4
        (televised) web/controllers/api/v1/shows_controller.ex:1: Televised.Api.V1.ShowsController.phoenix_controller_pipeline/2
        (televised) lib/phoenix/router.ex:265: Televised.Router.dispatch/2
        (televised) web/router.ex:1: Televised.Router.do_call/2
        (televised) lib/televised/endpoint.ex:1: Televised.Endpoint.phoenix_pipeline/1
        (televised) lib/plug/debugger.ex:90: Televised.Endpoint."call (overridable 3)"/2
        (televised) lib/phoenix/endpoint/render_errors.ex:34: Televised.Endpoint.call/2
        (plug) lib/plug/adapters/cowboy/handler.ex:15: Plug.Adapters.Cowboy.Handler.upgrade/4
        (cowboy) src/cowboy_protocol.erl:442: :cowboy_protocol.execute/4
```

**Comment by tpitale** [comment]
I would have assumed this line would handle this: https://github.com/devinus/poison/blob/master/lib/poison/encoder.ex#L69

**Comment by tpitale** [comment]
The inspect of the record I'm trying to encode. I'm guessing it's the `description: nil` part.

```
%Televised.Show{__meta__: #Ecto.Schema.Metadata<:loaded>,
 airs_at: #Ecto.Time<03:00:00>,
 created_at: #Ecto.DateTime<2015-02-05T20:12:10.232576Z>, description: nil,
 duration: 60, external_id: 28108, id: 42, name: "Don Francisco presenta",
 season_count: 10, status: 0,
 updated_at: #Ecto.DateTime<2015-02-05T20:12:10.232576Z>}
```

**Comment by tpitale** [comment]
Related: https://coderwall.com/p/fhsehq/fix-encoding-issue-with-ecto-and-poison and https://github.com/elixir-lang/ecto/issues/840
